use Project;
Select * from customers;
Select * from Orders;
Select * from Restaurants;


-- Q1. Display all completed orders along with customer name and restaurant name.

SELECT 
    o.order_id,
    c.customer_name,
    r.restaurant_name,
    o.order_amount,
    o.order_status
FROM orders AS o
INNER JOIN customers AS c
    ON o.customer_id = c.customer_id
INNER JOIN restaurants AS r
    ON o.restaurant_id = r.restaurant_id
WHERE o.order_status = 'Completed';



-- Q2. Find the total revenue generated by each restaurant.

SELECT 
    r.restaurant_name,
    SUM(o.order_amount) AS total_revenue
FROM restaurants AS r
INNER JOIN orders AS o
    ON r.restaurant_id = o.restaurant_id
GROUP BY r.restaurant_name
ORDER BY total_revenue DESC;



-- Q3. Show the total number of orders placed by each customer.

SELECT 
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers AS c
LEFT JOIN orders AS o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_name
ORDER BY total_orders DESC;


-- Find the average order amount for each city.

SELECT 
    c.city,
    AVG(o.order_amount) AS average_order_amount
FROM customers AS c
INNER JOIN orders AS o
    ON c.customer_id = o.customer_id
GROUP BY c.city
ORDER BY average_order_amount DESC;


-- Q5. Categorize orders as Low, Medium, and High based on order amount.

SELECT 
    order_id,
    order_amount,
    CASE
        WHEN order_amount < 500 THEN 'Low'
        WHEN order_amount BETWEEN 500 AND 1000 THEN 'Medium'
        ELSE 'High'
    END AS order_category
FROM orders;


-- Q6. Display restaurants whose average order value is greater than the overall average order value.

SELECT 
    r.restaurant_name,
    AVG(o.order_amount) AS average_order_value
FROM restaurants AS r
INNER JOIN orders AS o
    ON r.restaurant_id = o.restaurant_id
GROUP BY r.restaurant_name
HAVING AVG(o.order_amount) > (
    SELECT AVG(order_amount)
    FROM orders
);



-- Q7. Find customers who have never placed any orders.

SELECT 
    c.customer_id,
    c.customer_name
FROM customers AS c
LEFT JOIN orders AS o
    ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;

-- zero customers


-- Q8. Show the top 5 customers based on total spending

SELECT 
    c.customer_name,
    SUM(o.order_amount) AS total_spending
FROM customers AS c
INNER JOIN orders AS o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_name
ORDER BY total_spending DESC
LIMIT 5;



-- Q9. Find the most frequently used payment method

SELECT 
    payment_method,
    COUNT(*) AS payment_count
FROM orders
GROUP BY payment_method
ORDER BY payment_count DESC
LIMIT 1;


-- Q10. Calculate the running total of revenue by order date

SELECT 
    order_date,
    order_amount,
    SUM(order_amount) OVER (
        ORDER BY order_date
    ) AS running_revenue
FROM orders;



-- Q11. Rank restaurants based on total revenue generated

SELECT 
    r.restaurant_name,
    SUM(o.order_amount) AS total_revenue,
    RANK() OVER (
        ORDER BY SUM(o.order_amount) DESC
    ) AS revenue_rank
FROM restaurants AS r
INNER JOIN orders AS o
    ON r.restaurant_id = o.restaurant_id
GROUP BY r.restaurant_name;



-- Q12. Find the second highest order amount

SELECT MAX(order_amount) AS second_highest
FROM orders
WHERE order_amount < (
    SELECT MAX(order_amount)
    FROM orders
);



-- Q13. Find customers who placed more orders than the average number of orders per customer


SELECT 
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers AS c
INNER JOIN orders AS o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(o.order_id) > (
    SELECT AVG(order_count)
    FROM (
        SELECT 
            customer_id,
            COUNT(order_id) AS order_count
        FROM orders
        GROUP BY customer_id
    ) AS customer_orders
);


-- Q14. Display the top 3 restaurants in each city based on total orders received.


Select * from(
Select r.restaurant_name , r.city , count(o.order_id) as Total_orders , RANK() OVER (
        PARTITION BY r.city
        ORDER BY COUNT(o.order_id) DESC
    ) AS restaurant_rank from restaurants as r join orders as o on r.restaurant_id = o.restaurant_id 
Group by  r.restaurant_name , r.city ) as Ranked_restaurants where restaurant_rank <=3 order by city, restaurant_rank desc;


-- Q15. Calculate month-wise revenue and show the previous month revenue

SELECT 
    DATE_FORMAT(order_date, '%Y-%m') AS order_month,
    SUM(order_amount) AS monthly_revenue
FROM orders
GROUP BY DATE_FORMAT(order_date, '%Y-%m');